name: Deploy to neocities

# only run on changes to main. Use main or master depending on whatever your default branch is called. 
on:
  push:
    branches:
      - main

concurrency: # prevent concurrent deploys doing strange things
  group: deploy-to-neocities
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4 # grabs your repository's files
    - name: Install cmark
      run: |
        sudo apt-get install -y cmark
    - name: Build the site
      run: make
    - name: Deploying to Neocities
      uses: bcomnes/deploy-to-neocities@v2
      with:
        api_token: ${{ secrets.NEOCITIES_API_TOKEN }}
        cleanup: true # deletes all files that aren't in your repository
        dist_dir: public
